// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PetShopApp.Data;

#nullable disable

namespace PetShopApp.Migrations
{
    [DbContext(typeof(PetShopContext))]
    partial class PetShopContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PetShopApp.Models.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnimalId"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PictureName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AnimalId");

                    b.HasIndex("CategoryId");

                    b.ToTable("animals");

                    b.HasData(
                        new
                        {
                            AnimalId = 1,
                            Age = 2,
                            CategoryId = 1,
                            Description = "\r\nBears are mammals that belong to the family Ursidae. They can be as small as four feet long and about 60 pounds (the sun bear) to as big as eight feet long and more than a thousand pounds (the polar bear). They're found throughout North America, South America, Europe, and Asia.",
                            Name = "Bear",
                            PictureName = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTYY1GGaVgrCod3zB5wcoamtjiH0XwEAd8hKBIc4UKG5CjkjVtEPYxA7RP8dpqNTrL_ctk&usqp=CAU"
                        },
                        new
                        {
                            AnimalId = 2,
                            Age = 3,
                            CategoryId = 1,
                            Description = "\r\nEasily recognized by its coat of reddish-orange with dark stripes, the tiger is the largest wild cat in the world. The big cat's tail is three feet long. On average the big cat weighs 450 pounds, about the same as eight ten-year-old kids.",
                            Name = "Tiger",
                            PictureName = "https://animals.net/wp-content/uploads/2018/09/Tiger-2.jpg"
                        },
                        new
                        {
                            AnimalId = 3,
                            Age = 2,
                            CategoryId = 1,
                            Description = "\r\nWhales are the largest animals on Earth and they live in every ocean. The massive mammals range from the 600-pound dwarf sperm whale to the colossal blue whale, which can weigh more than 200 tons and stretch up to 100 feet long—almost as long as a professional basketball court.",
                            Name = "Whale",
                            PictureName = "https://nationaltoday.com/wp-content/uploads/2021/12/Humpback-Whale-Awareness-Month--640x514.jpg"
                        },
                        new
                        {
                            AnimalId = 4,
                            Age = 10,
                            CategoryId = 2,
                            Description = "\r\nturtle, any reptile with a body encased in a bony shell, including tortoises. Although numerous animals, from invertebrates to mammals, have evolved shells, none has an architecture like that of turtles. The turtle shell has a top (carapace) and a bottom (plastron).",
                            Name = "Turtels",
                            PictureName = "https://assets.petco.com/petco/image/upload/f_auto,q_auto/aquatic-turtle-care-sheet-hero"
                        },
                        new
                        {
                            AnimalId = 5,
                            Age = 8,
                            CategoryId = 2,
                            Description = "\r\nCrocodiles have powerful jaws with many conical teeth and short legs with clawed webbed toes. They share a unique body form that allows the eyes, ears, and nostrils to be above the water surface while most of the animal is hidden below. The tail is long and massive, and the skin is thick and plated.",
                            Name = "Crocodile",
                            PictureName = "https://www.stockland.com.au/~/media/shopping-centre/common/everyday-ideas/kids/crocodile/0518_stocklandnational_crocodiles_900x6753.ashx"
                        },
                        new
                        {
                            AnimalId = 6,
                            Age = 4,
                            CategoryId = 2,
                            Description = "\r\nsnake, Any member of about 19 reptile families (suborder Serpentes, order Squamata) that has no limbs, voice, external ears, or eyelids, only one functional lung, and a long, slender body. About 2,900 snake species are known to exist, most living in the tropics. Their skin is covered with scales.",
                            Name = "Snake",
                            PictureName = "https://i.natgeofe.com/n/d742b985-727d-4f14-85ff-5294fc44ef5e/snakes_02_2x1.jpg"
                        },
                        new
                        {
                            AnimalId = 7,
                            Age = 5,
                            CategoryId = 3,
                            Description = "Ostriches are large, flightless birds that have long legs and a long neck that protrudes from a round body. Males have bold black-and-white coloring that they use to attract females. Females, on the other hand, are light brown. Ostriches are bigger than any other bird in the",
                            Name = "Ostrich",
                            PictureName = "https://cdn.mos.cms.futurecdn.net/tMnjLRtEm47ueTPt9Rkyxd-1200-80.jpg"
                        },
                        new
                        {
                            AnimalId = 8,
                            Age = 7,
                            CategoryId = 3,
                            Description = " peacock is a shiny blue bird who fans out his large colorful iridescent tail feathers, especially when he's flirting with the peahens. A peacock is a male peafowl. A male peacock is more flamboyant than his female counterpart — he's the one with those long brilliant tail feathers marked with eye-like designs.",
                            Name = "Peacook",
                            PictureName = "https://animalcorner.org/wp-content/uploads/2015/02/Peafowl-Peacock.png"
                        },
                        new
                        {
                            AnimalId = 9,
                            Age = 11,
                            CategoryId = 3,
                            Description = "an eagle is any bird of prey more powerful than a buteo. An eagle may resemble a vulture in build and flight characteristics but has a fully feathered (often crested) head and strong feet equipped with great curved talons. A further difference is in foraging habits: eagles subsist mainly on live prey.",
                            Name = "Eagle",
                            PictureName = "https://onekindplanet.org/wp-content/uploads/2016/09/az_bald-eagle-520x294.jpg"
                        },
                        new
                        {
                            AnimalId = 10,
                            Age = 2,
                            CategoryId = 4,
                            Description = "marine and freshwater food fish, Salmo salar, of the family Salmonidae, having pink flesh, inhabiting waters off the North Atlantic coasts of Europe and North America near the mouths of large rivers, which it enters to spawn.",
                            Name = "Salmon",
                            PictureName = "https://cdn.britannica.com/50/117550-050-874E841A/Atlantic-salmon.jpg"
                        },
                        new
                        {
                            AnimalId = 11,
                            Age = 2,
                            CategoryId = 4,
                            Description = "Goldfish have two sets of paired fins and three sets of single fins. They don't have barbels, sensory organs some fish have that act like taste buds. Nor do they have scales on their heads. They also don't have teeth and instead crush their food in their throats.",
                            Name = "Goldfish",
                            PictureName = "https://fish-guppy.com/wp-content/uploads/2020/09/gold-fish-start-2.jpg"
                        },
                        new
                        {
                            AnimalId = 12,
                            Age = 3,
                            CategoryId = 4,
                            Description = "The guppy is a small fish. Males are significantly smaller than females, measuring just 0.6-1.4 in (1.5-3.5 cm) long. Females, at about 1.2-2.4 in (3-6 cm) in length, are about twice the size. Males also tend to be more colorful, and extravagant, with ornamental fins absent in the females.",
                            Name = "Guppy",
                            PictureName = "https://cdn-acgla.nitrocdn.com/bvIhcJyiWKFqlMsfAAXRLitDZjWdRlLX/assets/static/optimized/rev-5131b73/wp-content/uploads/2020/09/shutterstock_642230203-1.jpg"
                        },
                        new
                        {
                            AnimalId = 13,
                            Age = 3,
                            CategoryId = 5,
                            Description = "Spiders are arthropods that have eight legs. They have more legs and different body parts than insects, and they also don't move around in the same way insects do. Spiders are in the arachnid class, but not all arachnids are spiders. There are about 40,000 known species of spiders.",
                            Name = "Spider",
                            PictureName = "https://i.pinimg.com/originals/3d/6b/58/3d6b58d97408757e577ee4c584c16087.jpg"
                        },
                        new
                        {
                            AnimalId = 14,
                            Age = 1,
                            CategoryId = 5,
                            Description = "\r\nMost ladybugs have oval, dome-shaped bodies with six short legs. Depending on the species, they can have spots, stripes, or no markings at all. Seven-spotted ladybugs are red or orange with three spots on each side and one in the middle. They have a black head with white patches on either side.",
                            Name = "Ladybug",
                            PictureName = "https://i.natgeofe.com/k/d987f7b2-1895-4978-9216-3f365ea51a34/ladybug-daisy_4x3.jpg"
                        },
                        new
                        {
                            AnimalId = 15,
                            Age = 1,
                            CategoryId = 5,
                            Description = "Scorpions are arthropods, they have eight legs, two pedipalps, and a tail with a venom-injecting barb. Scorpions have two venom glands that produce venom used in hunting and self defense. Scorpions do not have bones instead they have an exoskeleton made of chitin, which is similar to the shell of a shrimp",
                            Name = "Scorpion",
                            PictureName = "https://upload.wikimedia.org/wikipedia/commons/f/fe/Scorpion_Photograph_By_Shantanu_Kuveskar.jpg"
                        });
                });

            modelBuilder.Entity("PetShopApp.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Mammals"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Reptiles"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Birds"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Fish"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Invertebrates"
                        });
                });

            modelBuilder.Entity("PetShopApp.Models.Comments", b =>
                {
                    b.Property<int>("CommentsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommentsId"));

                    b.Property<int>("AnimalId")
                        .HasColumnType("int");

                    b.Property<string>("comment")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CommentsId");

                    b.HasIndex("AnimalId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            CommentsId = 1,
                            AnimalId = 9,
                            comment = "So Powerfull"
                        },
                        new
                        {
                            CommentsId = 2,
                            AnimalId = 10,
                            comment = "something"
                        },
                        new
                        {
                            CommentsId = 3,
                            AnimalId = 11,
                            comment = "something"
                        },
                        new
                        {
                            CommentsId = 4,
                            AnimalId = 12,
                            comment = "something"
                        },
                        new
                        {
                            CommentsId = 5,
                            AnimalId = 13,
                            comment = "something"
                        },
                        new
                        {
                            CommentsId = 6,
                            AnimalId = 14,
                            comment = "something"
                        },
                        new
                        {
                            CommentsId = 7,
                            AnimalId = 15,
                            comment = "something"
                        },
                        new
                        {
                            CommentsId = 8,
                            AnimalId = 10,
                            comment = "cute!"
                        },
                        new
                        {
                            CommentsId = 9,
                            AnimalId = 9,
                            comment = "So Cute"
                        });
                });

            modelBuilder.Entity("PetShopApp.Models.Animal", b =>
                {
                    b.HasOne("PetShopApp.Models.Category", "Category")
                        .WithMany("Animals")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("PetShopApp.Models.Comments", b =>
                {
                    b.HasOne("PetShopApp.Models.Animal", "Animal")
                        .WithMany("Comments")
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Animal");
                });

            modelBuilder.Entity("PetShopApp.Models.Animal", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("PetShopApp.Models.Category", b =>
                {
                    b.Navigation("Animals");
                });
#pragma warning restore 612, 618
        }
    }
}
